# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'sridharthangella1 Docker Hub'
        repository: 'sridharthangella1/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/DockerFile'
        tags: |
          $(tag)
- stage: Provision
  displayName: 'Terraforming on Azure'
  dependsOn: Build
  jobs:
  - job: Provision
    displayName: 'Provisioning Container Instance'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: TerraformEnvVars
    steps:
    - script: |
        set -e

        terraform init -input=false
        terraform apply -input=false -auto-approve
      name: 'RunTerraform'
      displayName: 'Run Terraform'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBCRIPTION_ID: $(ARM_SUBCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)





